/**
 * @author Subrata
 */

import './not-found/not-found';
import './login/index';
import './resetPassword/index';
import './verifyEmail/index';
import './user/index';
import './vanSaleUser/index';
import './role/index';
// import './designation/index';
import './order/index';
// import './orderHistory/index';
import './orderApprove/index';
import './salesDashboard/index';
import './adminDashboard/index';
import './delivery/index';
import './dispatch/index';
import './collectionDueToday/index';
import './dispatchForDelivery/index';
import './accessDenied/accessDenied';
import './dispatchDelivered/index';
// import './dispatchRejected/index';
import './salesReturn/index';
import './salesReturnApprove/index';
// import './deliveryBoyHistory/index';
// import './deliveryBoyHistoryForUsers/index';
import './creditInvoice/index';
import './creditInvoiceApprove/index';
import './salesQuotation/index';
import './quotationApprove/index';
import './approvedOrders/index';
import './approvedQuotations/index';
import './pickList/index';
import './invoice/index';
import './collectionList/index';
import './deliveryHistory/index';
import './invoiceHistory/index';
import './arInvoice+Payment/index';
import './creditNote/index';
import './creditNoteApprove/index';
import './orderOnHold/index';
import './orderRejected/index';
import './quotationOnHold/index';
import './quotationRejected/index';
import './approvedCreditInvoice/index';
import './creditInvoiceOnHold/index';
import './creditInvoiceRejected/index';
import './approvedSalesReturn/index';
import './salesReturnOnHold/index';
import './approvedCreditNote/index';
import './creditNoteRejected/index';
import './creditNoteOnHold/index';
import './salesReturnRejected/index';
import './deliveryDispatch/index';
import './dispatch/index';
import './dispatchDelivered/index';
import './dispatchForDelivery/index';
import './stockTransfer/index';
import './stockTransferApproval/index';
import './stockTransferApproved/index';
import './stockTransferOnHold/index';
import './stockTransferRejected/index';
// import './approvedOrdersForUser/index';
import './lead/index';
// import './databaseSync/index';
import './orderReport/index';
import './sQReport/index';
import './systemConfig/index';
import './arInvoicePaymentReport/index';
import './creditInvoiceReport/index';
import './salesReturnReport/index';
import './creditNoteReport/index';
import './salesQuotationSenior/index';
import './orderSenior/index';
import './arInvoiceSenior/index';
import './branchTransferReport/index';
import './branchTransfer/index';
import './branchTransferIssue/index';
import './deliveryManagerHistory/index';
import './pickListHistory/index';
import './collectionReport/index';
import './stockTransferReport/index';
import './branchTransferIssued/index';
import './invoiceReport/index';
import './deliveryAssignedHistory/index';
import './deliveryReport/index';
import './purchaseInvoice/index';
// import './orderOwnReport/index';
// import './sQOwnReport/index';
// import './arInvoiceOwnReport/index';
// import './creditInvoiceOwnReport/index';
// import './salesReturnOwnReport/index';
// import './creditNoteOwnReport/index';
// import './collectionOwnReport/index';
import './branchTransferIssuedReport/index';
import './purchaseInvoiceReport/index';
// import './approvedOrdersDashboard/index';
// import './pendingOrdersDashboard/index';
// import './rejectedOrdersDashboard/index';
// import './onHoldOrdersDashboard/index';
// import './approvedQuotationsDashboard/index';
// import './pendingQuotationsDashboard/index';
// import './rejectedQuotationsDashboard/index';
// import './onHoldQuotationsDashboard/index';
// import './activities/index';
import './pendingOrders/index';
import './invoiceApprove/index';
import './invoiceOnHold/index';
import './invoiceRejected/index';
import './approvedInvoice/index';
import './pendingInvoices/index';
// import './posCreditInvoice/index';
// import './posInvoice+Payment/index';
// import './pendingCreditInvoice/index';
import './routeReport/index';
import './routeAssignReport/index';
import './routeCheckInOutReport/index';
import './map/index';
import './pendingArInvoicePayment/index';
import './pendingPosInvoices/index';
import './routeGroup/index';
import './routeAssign/index';
import './attendance/index';
import './routeApprove/index';
import './approvedRoutes/index';
import './rejectedRoutes/index';
import './skipRemarks/index';
import './leadQuotation/index';
import './salesmanWiseLocReport/index';
import './skippedCustomerReport/index';
import './noTransactionReport/index';
import './salesSummaryReport/index';
import './stockSummaryReport/index';
import './superAdminDashboard/index';
import './targetOutletReport/index';
import './callRateReport/index';
import './strikeRateReport/index';
import './cxoDashboard/index';
import './warehouseStockReport/index';
import './itemWiseSalesReport/index';
import './numericalDistributon/index';
import './branchWiseStockReport/index';
import './weightageDistributionReport/index';
import './coverageDistributionReport/index';
import './expenseReport/index'
import './expenseCategory/index';
import './locationManagement/index';


import './branch/index';
import './wareHouse/index';
import './wareHouseStock/index';
import './customer/index';
import './customerAddress/index';
import './customerPriceList/index';
import './item/index';
import './itemCategory/index';
import './itemGetPrice/index';
import './itemPriceList/index';
import './unit/index';
import './tax/index';
import './returnAction/index';
import './returnReason';
